# Generated by Django 5.2.4 on 2025-07-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_appointment_doctor_appointment_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
