# Generated by Django 5.2.4 on 2025-08-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Doctor", "Doctor"),
                    ("Patient", "Patient"),
                ],
                default="Patient",
                max_length=20,
            ),
        ),
    ]
