# Generated by Django 5.2.4 on 2025-08-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Patient', 'Patient'), ('Nurse', 'Nurse'), ('Receptionist', 'Receptionist')], default='Patient', max_length=20),
        ),
    ]
