# Generated by Django 5.2.4 on 2025-08-10 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("medical_records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="appointment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescription",
                to="appointments.appointment",
            ),
        ),
    ]
